#### Import numpy as np and print the version number.



In [6]:
import numpy as np
numpy.__version__

'1.16.2'

#### Create a 1D array of numbers from 0 to 9

In [8]:
array1d=np.arange(9)

In [9]:
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Create a 3×3 numpy array of all True’s

In [11]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Extract all odd numbers from arr

In [13]:
oddnos=list(filter(lambda x:x%2!=0,array1d))

In [14]:
oddnos

[1, 3, 5, 7]

In [17]:
array1d[array1d%2!=0]

array([1, 3, 5, 7])

### Replace all odd numbers in arr with -1

In [20]:
array1d[array1d%2!=0]=-1

In [21]:
array1d

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

### Convert a 1D array to a 2D array with 2 rows

In [24]:
np.reshape(array1d,(3,3))

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

### Stack arrays a and b vertically

- a = np.arange(10).reshape(2,-1)
- b = np.repeat(1, 10).reshape(2,-1)

In [30]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack(a))
print(np.vstack(b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


### Stack the arrays a and b horizontally. 

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.hstack(a))
print(np.hstack(b))

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1 1]


### Get the positions where elements of a and b match

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])